@baseUrl = http://localhost:4004/api

# Categories
@resourceName=categories

# @name getAllCategories
GET {{baseUrl}}/{{resourceName}}

###

# @name addNewCategory
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "name": "Laptop"
}

###

# @name updateCategory
PATCH {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
  "name": "New Laptop"
}

###

# @name removeCategory
DELETE {{baseUrl}}/{{resourceName}}/2
